### ISSUE TITLE
Wont export to CAD

### ISSUE THREAD

**Issue by Wehler** [mvernacc/aerospike-nozzle-design-gui#4]
Hi
Seem to be having some issues when exporting to CAD. It just makes empty .txt files, when i push the button

![Aerospike error](https://user-images.githubusercontent.com/70333483/91459547-0a582800-e887-11ea-966f-88adbd55639f.JPG)

I am very new to this:)

Thank you

**Comment by mvernacc** [comment]
@Wehler , thanks for pointing this out - turns out I broke the export function with a change I made a few months ago. I fixed it here https://github.com/mvernacc/aerospike-nozzle-design-gui/commit/8d2fa75cf501ab8fbf51ace541915ff1596904b2. Do `git pull` in your local branch to download the fix.

p.s. I see this is your first ever issue! Nice :)
